@startuml
title Provisioning a workload on the TFGrid

autonumber
actor "User" as user
actor "Farmer" as farmer
database "TF Explorer" as explorer
database Blockchain as blockchain
boundary Node as node

== Price definition ==
farmer -> explorer: Farmer set the price of its Resource units
== Resource research ==
activate explorer
user -> explorer: User look where to deploy the workload
user <- explorer: Gives detail about the farmer owning the node selected
== Pool creation ==
user -> explorer: Create pool add all nodes (or a subset) from the farmer nodes
explorer -> user: return a list of transaction to execute on the blockchain
user -> blockchain: execute transactions
explorer <-> blockchain: verify transactions are done
== Resource reservation  ==
user -> explorer: write description of the workload, tied to a pool.
== Reservation processing  ==
explorer -> explorer: Checks pool resources
explorer -> explorer: reservation status changed to `deploy`
== Resource provisioning  ==
node <-> explorer: read description of the workloads
node -> node: provision workload
alt provision successfull
    node -> explorer: write result of the provisining
    user <- explorer: read the connection information to his workload
else provision error
    node -> explorer: write result of the provisining
    explorer -> explorer: cancel reservation
end
deactivate explorer
== Resource monitoring ==
user <-> node: use / monitor workload
@enduml
